# Generated by Django 4.2.3 on 2023-08-07 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0003_alter_students_address_alter_students_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(default=2023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(),
        ),
    ]
