# Generated by Django 4.2.3 on 2023-08-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0004_alter_students_address_alter_students_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms_app.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
