# Generated by Django 4.2.3 on 2023-08-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0005_alter_students_address_alter_students_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_app.courses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
